apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <filter kubernetes.var.log.containers.laravel-app**>
      @type kubernetes_metadata
    </filter>
    <match kubernetes.var.log.containers.laravel-app**>
      @type elasticsearch
      hosts elasticsearch.default.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix laravel-app
      include_tag_key true
      type_name _doc
    </match>
